name: hello-world
on: push
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: install makefile
        run: apt install make
      - name: change to makefile directory
        run: cd ../..
      - name: run Makefile
        run: make say-hello
